runtime: python27
api_version: 1
threadsafe: true
instance_class: F4
service: frontsocketsprueba
handlers:
  - url: /(.*\.(gif|png|jpg|ico|txt|js|css|html|json|svg|woff|ttf|eot))
    static_files: www/\1
    upload: www/.*\.(gif|png|jpg|ico|txt|js|css|html|json|svg|woff|ttf|eot)
    secure: always
    redirect_http_response_code: 301
  - url: /.*
    static_files: www/index.html
    upload: www/index.html
    secure: always
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic